//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekpad
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtrans_beli
    {
        public string db_id { get; set; }
        public string db_va_id { get; set; }
        public int db_amount { get; set; }
        public string db_hb_id { get; set; }
        public double db_subtotal { get; set; }
    
        public virtual htrans_beli htrans_beli { get; set; }
        public virtual variant variant { get; set; }
    }
}
