//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekpad
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtrans_service
    {
        public string ds_id { get; set; }
        public string ds_se_id { get; set; }
        public string ds_hs_id { get; set; }
        public double ds_subtotal { get; set; }
    
        public virtual htrans_service htrans_service { get; set; }
        public virtual service service { get; set; }
    }
}
