//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekpad
{
    using System;
    using System.Collections.Generic;
    
    public partial class htrans_beli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public htrans_beli()
        {
            this.dtrans_beli = new HashSet<dtrans_beli>();
        }
    
        public string hb_id { get; set; }
        public System.DateTime hb_date { get; set; }
        public string hb_invoice_number { get; set; }
        public double hb_total { get; set; }
        public string hb_customerid { get; set; }
        public int hb_status { get; set; }
        public string hb_employeeid { get; set; }
        public string hb_di_id { get; set; }
    
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtrans_beli> dtrans_beli { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
