//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekpad
{
    using System;
    using System.Collections.Generic;
    
    public partial class htrans_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public htrans_service()
        {
            this.dtrans_service = new HashSet<dtrans_service>();
        }
    
        public string hs_id { get; set; }
        public System.DateTime hs_date { get; set; }
        public string hs_invoice_number { get; set; }
        public double hs_total { get; set; }
        public string hs_customerid { get; set; }
        public int hs_status { get; set; }
        public string hs_employeeid { get; set; }
        public string hs_di_id { get; set; }
    
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtrans_service> dtrans_service { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
