//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekpad
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public service()
        {
            this.dtrans_service = new HashSet<dtrans_service>();
        }
    
        public string se_id { get; set; }
        public string se_name { get; set; }
        public double se_price { get; set; }
        public string se_sc_id { get; set; }
        public string se_in_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtrans_service> dtrans_service { get; set; }
        public virtual instrument instrument { get; set; }
        public virtual service_category service_category { get; set; }
    }
}
