//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyekpad
{
    using System;
    using System.Collections.Generic;
    
    public partial class variant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public variant()
        {
            this.dtrans_beli = new HashSet<dtrans_beli>();
        }
    
        public string va_id { get; set; }
        public string va_al_id { get; set; }
        public string va_co_id { get; set; }
    
        public virtual alatmusik alatmusik { get; set; }
        public virtual color color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dtrans_beli> dtrans_beli { get; set; }
    }
}
